[package]
name = "db_drawio_sync"
version = "0.1.0"
authors = ["Andrew <snakent@gmail.com>"]
edition = "2021"
rust-version = "1.73"

[dependencies]
log = "0.4"
egui = "0.24"
once_cell = "1.17"
regex = "1.8"
eframe = "0.24"
egui_logger = "0.4.0"