[package]
name = "db_drawio_sync"
version = "0.1.0"
authors = ["Riful17 <snakent@gmail.com>"]
edition = "2021"
rust-version = "1.73"

[dependencies]
sqlparser = "0.40.0"
log = { version = "0.4.20", features = [] }
env_logger = "0.10.1"
chrono = "0.4.31"